version: "3.2"
services:
  web: 
    build: ./todo-app/
    ports:
      - "4200:80"
  webapi:
    build: ./todo-api/
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "Suporte_123456"
      ACCEPT_EULA: "Y"

